#!/usr/bin/env python

import sys
import getopt
import lib.config
import lib.modul

if __name__ == "__main__":
    config_path = 'config/backuprestore.example'
    try:
        opts, args = getopt.getopt(sys.argv[1:],"hc",["config="])
        for opt, arg in opts:
            if opt == '-h':
                print("br-service -c <configfile>")
                sys.exit()
            elif opt in ("-c", "--config"):
                config_path = arg
    except getopt.GetoptError:
        print("Error with input\nbr-service -c <configfile>")
    lib.config.init(config_path)
    lib.modul.backup(lib.config.CONFIG)
